eureka:
  instance:
    hostname: localhost
    appname: auth_service
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
    fetch-registry: false
    register-with-eureka: false
spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://wyvernpserver.tech:5432/org_demo
    hikari:
      username: sa
      password: ThanhPhong2506
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: 95.lethanhphong.dvd@gmail.com
    password: ysaiyhovuuwvfuwl
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    consumer:
      bootstrap-servers: kafka.wyvernpserver.tech:9092
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.connect.json.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: tech.chickies.notificationserver.mk.consumer.ExportMessage
      group-id: mk
server:
  port: 8006
