eureka:
  instance:
    hostname: localhost
    appname: auth_service
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
    fetch-registry: false
    register-with-eureka: false
spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://wyvernpserver.tech:5432/org_demo
    hikari:
      username: sa
      password: ThanhPhong2506
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: 95.lethanhphong.dvd@gmail.com
    password: ysaiyhovuuwvfuwl
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8006
